# Generated by Django 4.0.5 on 2022-06-09 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blodTypeName', models.CharField(max_length=254, verbose_name='فصيلة الدم')),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='المرحلة')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blodType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blodType', to='accounts.blodstype'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='accounts.levels', verbose_name='المرحلة'),
        ),
    ]
