# Generated by Django 4.0.5 on 2022-06-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blodstype_levels_userprofile_blodtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diseases',
            field=models.CharField(blank=True, max_length=254, verbose_name='الامراض المزمنة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='importentNumber',
            field=models.CharField(blank=True, max_length=254, verbose_name='رقم اخر مهم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='note',
            field=models.TextField(blank=True, verbose_name='ملاحظات مهمة'),
        ),
    ]
