# Generated by Django 4.0.5 on 2022-06-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_diseases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pass_id',
            field=models.CharField(default='sT2h!t', max_length=254, verbose_name='كلمة المرور عند المرور'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blodType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blodType', to='accounts.blodstype', verbose_name='فصيلة الدم'),
        ),
    ]
