# Generated by Django 4.0.5 on 2022-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_pass_id_alter_userprofile_blodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pass_id',
            field=models.CharField(default='748cQJKNXj)ToPH', max_length=254, unique=True, verbose_name='كلمة المرور عند المرور'),
        ),
    ]
