# Generated by Django 4.0.5 on 2022-06-23 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_pass_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='تاريخ انشاء الملف الشخصي'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_Enabled',
            field=models.BooleanField(default=True, verbose_name='هل هذا الملف الشخصي مفعل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pass_id',
            field=models.CharField(default='MD1AG', max_length=254, unique=True, verbose_name='كلمة المرور عند المرور'),
        ),
        migrations.CreateModel(
            name='PassData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, verbose_name='اسم الطالب')),
                ('school', models.CharField(max_length=254, verbose_name='اسم المدرسة')),
                ('GuardianNumber', models.CharField(max_length=254, verbose_name='رقم ولي الامر')),
                ('is_Definded', models.BooleanField(default=False, verbose_name='هل هو موجود في جهات الاتصال واتساب')),
                ('passDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ المرور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='ملف الشخصي للمستخدم')),
            ],
        ),
    ]
