# Generated by Django 4.0.5 on 2022-06-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_created_date_userprofile_is_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passdata',
            name='is_sended',
            field=models.BooleanField(default=False, verbose_name='هل تم ارسال الرسالة عبر الواتس'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pass_id',
            field=models.CharField(default='2QKZW', max_length=254, unique=True, verbose_name='كلمة المرور عند المرور'),
        ),
    ]
