# Generated by Django 4.0.5 on 2022-06-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passdata_is_sended_alter_userprofile_pass_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefindedNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=254, verbose_name='الرقم')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pass_id',
            field=models.CharField(default='QXH91', max_length=254, unique=True, verbose_name='كلمة المرور عند المرور'),
        ),
    ]
