# Generated by Django 4.0.5 on 2022-07-08 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_defindednumbers_alter_userprofile_pass_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='passdata',
            name='passDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 12, 28, 13, 868050, tzinfo=utc), verbose_name='تاريخ المرور'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='GuardianNumber',
            field=models.CharField(blank=True, max_length=254, verbose_name='رقم ولي الامر واتس اب'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 12, 28, 13, 867049, tzinfo=utc), null=True, verbose_name='تاريخ انشاء الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='importentNumber',
            field=models.CharField(blank=True, max_length=254, verbose_name='رقم اخر ولي الامر مهم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pass_id',
            field=models.CharField(default='UMNRU', max_length=254, unique=True, verbose_name='كلمة المرور عند المرور'),
        ),
    ]
