# Generated by Django 4.0.5 on 2022-07-08 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_options_alter_passdata_passdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passdata',
            name='passDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 12, 56, 33, 163987, tzinfo=utc), verbose_name='تاريخ المرور'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='GuardianNumber',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='رقم ولي الامر واتس اب'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 12, 56, 33, 162985, tzinfo=utc), null=True, verbose_name='تاريخ انشاء الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diseases',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='الامراض المزمنة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='importentNumber',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='رقم اخر ولي الامر مهم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات مهمة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pass_id',
            field=models.CharField(default='QC3XB', max_length=254, unique=True, verbose_name='كلمة المرور عند المرور'),
        ),
    ]
